Repository GaloisInc/crucible, pull requests merged in 2025-04, with the labels that each got.

#1365 Dockerfiles: Support both amd64 and arm64 builds
  .github/Dockerfile-crux-llvm
  .github/Dockerfile-crux-mir
Labels: CI

#1367 Dockerfiles: Revert from Ubuntu 24.04 to 22.04
  .github/Dockerfile-crux-llvm
  .github/Dockerfile-crux-mir
Labels: Docker

#1371 ci: Don't install LLVM in workflows that don't need it
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
Labels: CI

#1372 ci: Use `haskell-ci` for `crucible-{go,jvm,wasm}` build
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
Labels: CI

#1380 ci: Simplify Cabal/GHC compatibility check
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
Labels: CI

#1381 ci: Misc. version bumps
  .github/Dockerfile-crux-llvm
  .github/Dockerfile-crux-mir
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
  doc/dev.md
Labels: CI

#1382 ci: Separate caches for `crux-{llvm,mir}`
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
Labels: CI

#1377 Support GHC 9.10.1, drop 9.4.8
  .github/Dockerfile-crux-llvm
  .github/Dockerfile-crux-mir
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
  cabal.GHC-9.10.1.config
  cabal.GHC-9.6.7.config
  cabal.GHC-9.8.4.config
  cabal.project
  crucible-cli/crucible-cli.cabal
  crucible-debug/crucible-debug.cabal
  crucible-debug/src/Lang/Crucible/Debug/Style.hs
  crucible-debug/src/Lang/Crucible/Pretty.hs
  crucible-llvm-cli/crucible-llvm-cli.cabal
  crucible-llvm-debug/crucible-llvm-debug.cabal
  crucible-llvm-syntax/crucible-llvm-syntax.cabal
  crucible-llvm/crucible-llvm.cabal
  crucible-llvm/src/Lang/Crucible/LLVM/Globals.hs
  crucible-llvm/src/Lang/Crucible/LLVM/Translation/BlockInfo.hs
  crucible-symio/crucible-symio.cabal
  crucible-syntax/crucible-syntax.cabal
  crucible/crucible.cabal
  crucible/src/Lang/Crucible/Simulator/OverrideSim.hs
  crucible/src/Lang/Crucible/Utils/BitSet.hs
  crux-llvm/crux-llvm.cabal
  crux-llvm/test/Test.hs
  crux-mir/README.md
Labels: CI

#1387 `crux-mir-test`: Show diffs when tests fail
  crux-mir/test/Test.hs
Labels: crux, testing, UX, MIR

#1389 `crucible-mir`: Always store source positions in `Statement`s/`Terminator`s
  crucible-mir/CHANGELOG.md
  crucible-mir/src/Mir/GenericOps.hs
  crucible-mir/src/Mir/JSON.hs
  crucible-mir/src/Mir/Mir.hs
  crucible-mir/src/Mir/PP.hs
  crucible-mir/src/Mir/Pass/AllocateEnum.hs
  crucible-mir/src/Mir/Trans.hs
  crux-mir/CHANGELOG.md
  crux-mir/test/symb_eval/any/downcast_fail.good
  crux-mir/test/symb_eval/bytes/put_overflow.good
  crux-mir/test/symb_eval/concretize/assert.good
  crux-mir/test/symb_eval/crux/early_fail.good
  crux-mir/test/symb_eval/crux/fail_return.good
  crux-mir/test/symb_eval/crux/mixed_fail.good
  crux-mir/test/symb_eval/crux/multi.good
  crux-mir/test/symb_eval/crypto/bytes.good
  crux-mir/test/symb_eval/overrides/bad_symb1.good
  crux-mir/test/symb_eval/overrides/bad_symb2.good
  crux-mir/test/symb_eval/overrides/override2.good
  crux-mir/test/symb_eval/overrides/override5.good
  crux-mir/test/symb_eval/sym_bytes/construct.good
Labels: crucible, crux, MIR
