Repository GaloisInc/crucible, pull requests merged in 2025-02, with the labels that each got.

#1280 Check the repository owner in CI tasks
  .github/workflows/README.md
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
Labels: bug, CI

#1298 debug: Take a number of steps as an argument to `step`
  crucible-debug/src/Lang/Crucible/Debug.hs
  crucible-debug/src/Lang/Crucible/Debug/Command/Base.hs
  crucible-debug/src/Lang/Crucible/Debug/Context.hs
  crucible-debug/src/Lang/Crucible/Debug/Eval.hs
  crucible-debug/test-data/help.txt
  crucible-debug/test-data/reg.txt
  crucible-debug/test-data/step.txt
  crucible-debug/test-data/usage.txt
Labels: debugger

#1297 crux: Add a `--debug` flag to drop into the Crucible debugger
  crucible-debug/src/Lang/Crucible/Debug.hs
  crux-llvm/CHANGELOG.md
  crux-llvm/README.md
  crux-mir/CHANGELOG.md
  crux/CHANGELOG.md
  crux/crux.cabal
  crux/src/Crux.hs
  crux/src/Crux/Config/Common.hs
Labels: crux
