Repository GaloisInc/crucible, pull requests merged in 2025-03, with the labels that each got.

#1320 ci: Small improvements
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
Labels: CI

#1350 ci: Move GHC/Cabal compatibility check to improve caching
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
Labels: CI

#1331 crucible: Add a `GlobalPair` to `AbortedExit`
  crucible-symio/tests/TestMain.hs
  crucible/CHANGELOG.md
  crucible/src/Lang/Crucible/Simulator/ExecutionTree.hs
  crucible/src/Lang/Crucible/Simulator/Operations.hs
  crucible/src/Lang/Crucible/Simulator/OverrideSim.hs
Labels: crucible

#1328 crucible: Document the simulator "personality"
  crucible/src/Lang/Crucible/Simulator/ExecutionTree.hs
  crucible/src/Lang/Crucible/Simulator/OverrideSim.hs
Labels: crucible

#1358 `crux-mir` Dockerfile: Fix broken command substitution in `CRUX_RUST_LIBRARY_PATH`
  .github/Dockerfile-crux-mir
Labels: crux, CI, MIR, Docker

#1356 ci: Small changes
  .github/Dockerfile-crux-llvm
  .github/Dockerfile-crux-mir
  .github/ci.sh
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
  crux-llvm/svcomp/mk-svcomp-bindist.sh
  crux-mir/Concurrency.md
  crux-mir/README.md
Labels: CI

#1362 ci: Make use of parallelism, and don't retry builds
  .github/ci.sh
  .github/workflows/crucible-go-build.yml
  .github/workflows/crucible-jvm-build.yml
  .github/workflows/crucible-wasm-build.yml
  .github/workflows/crux-llvm-build.yml
  .github/workflows/crux-mir-build.yml
Labels: CI
